version: "3.8"
services:
  # webコンテナはnginxで構成
  web:
    image: nginx:latest
    ports:
      - "8989:80"
    depends_on:
      - app
    volumes:
      - ./Docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ../backend:/work/backend/laravel

  # appコンテナはPHP Laravelも後からインストールするので、Dockerfileに設定を記載
  app:
    build: ./Docker/php
    volumes:
      - ../backend:/work/backend/laravel
    depends_on:
      - db

  # dbコンテナはMySQLで構成する depends onによりdb→app→webの順にコンテナを立ち上げていく
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: rd_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - 4306:3306
    volumes:
      - ./Docker/db/conf:/etc/db/conf.d:rw
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8026:8026"

volumes:
  mysql-data:
